version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Da2d9asd
      MYSQL_DATABASE: licenta
      MYSQL_USER: dariusnicolae
      MYSQL_PASSWORD: sda@Da2d9asd
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  elasticsearch:
    image: elastic/elasticsearch:7.15.2
    container_name: elastic
    hostname: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=elastic
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=elastic
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  esdata:
    driver: local
  dbdata:
